---
- name: change expiration setting days
  become: true
  xml: 
    file: "{{ archiva.install_path }}/apache-archiva-{{ archiva.version }}/conf/archiva.xml"
    value: 99999
    xpath: /configuration/redbackRuntimeConfiguration/configurationProperties/security/policy/password/expiration/days

- name: change expiration setting enabled
  become: true
  xml: 
    file: "{{ archiva.install_path }}/apache-archiva-{{ archiva.version }}/conf/archiva.xml"
    value: false
    xpath: /configuration/redbackRuntimeConfiguration/configurationProperties/security/policy/password/expiration/enabled

- name: restart archiva1
  become: true
  service: name=archiva state=restarted

- name: "Config maven"
  become: false
  ignore_errors: true
  include: config-maven.yml